// Generated by Apple Swift version 4.0 (swiftlang-900.0.54.11 clang-900.0.31)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import UIKit;
@import Foundation;
@import CoreGraphics;
@import ObjectiveC;
#endif

#import "/Users/a1/Desktop/snakesdk swift 3.0 2 4.0version/snakesdk-Bridging-Header.h"

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("_CUSTOM_MODULE_NAME_")
@class UIImageView;
@class UILabel;
@class UIButton;
@class NSCoder;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_21AccountChooseViewCell")
@interface AccountChooseViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _imgIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblAccount;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnDelete;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class NSBundle;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_31AccountManagementViewController")
@interface AccountManagementViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTips;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPhone;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPhone;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPassword;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPassword;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _imgAccountType;
- (void)handlePassword;
- (void)handlePhone;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWebView;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_23AgreementViewController")
@interface AgreementViewController : UIViewController <UIWebViewDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWebBg;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)webViewDidStartLoad:(UIWebView * _Nonnull)webView;
- (void)webViewDidFinishLoad:(UIWebView * _Nonnull)webView;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_19AlertViewController")
@interface AlertViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vBackView;
- (void)viewDidLoad;
- (IBAction)onConfirmClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindow;
@class BaseResp;
@class UIApplication;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate, WXApiDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (void)onResp:(BaseResp * _Null_unspecified)resp;
- (void)applicationWillResignActive:(UIApplication * _Nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * _Nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * _Nonnull)application;
- (void)applicationWillTerminate:(UIApplication * _Nonnull)application;
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation SWIFT_WARN_UNUSED_RESULT;
- (BOOL)application:(UIApplication * _Nonnull)application handleOpenURL:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_15CountdownButton")
@interface CountdownButton : UIButton
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_26CurrentPhoneViewController")
@interface CurrentPhoneViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPhoneNumber;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnSwitch;
- (void)viewDidLoad;
- (IBAction)onChangeClickedWithSender:(UIButton * _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_17DismissModalSegue")
@interface DismissModalSegue : UIStoryboardSegue
- (void)perform;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nullable)identifier source:(UIViewController * _Nonnull)source destination:(UIViewController * _Nonnull)destination OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_22ExitGameViewController")
@interface ExitGameViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vBackVIew;
- (void)viewDidLoad;
- (IBAction)onCancelClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onGameCenterClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onExitClickedWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_33FecthVerifyCodeFillViewController")
@interface FecthVerifyCodeFillViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTips;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtVerifyCode;
@property (nonatomic, weak) IBOutlet CountdownButton * _Null_unspecified _btnVerifyCode;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnNext;
- (IBAction)onTextChanged:(UITextField * _Nonnull)sender;
- (void)viewDidLoad;
- (IBAction)onVerifyCodeClickedWithSender:(CountdownButton * _Nonnull)sender;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onNextClickedWithSender:(id _Nonnull)sender;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_33ForgotenAccountFillViewController")
@interface ForgotenAccountFillViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnNext;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtAccount;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblAccountTips;
- (IBAction)onAccountChanged:(UITextField * _Nonnull)sender;
- (IBAction)onNextClickedWithSender:(id _Nonnull)sender;
- (void)viewDidLoad;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_43ForgotenAccountVerifyCodeFillViewController")
@interface ForgotenAccountVerifyCodeFillViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblAccount;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPhone;
@property (nonatomic, weak) IBOutlet CountdownButton * _Null_unspecified _btnVerifyCode;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnNext;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblVerifyCode;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtVerifyCode;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onTextChanged:(UITextField * _Nonnull)sender;
- (IBAction)onVerifyCodeClickedWithSender:(id _Nonnull)sender;
- (IBAction)onNextClickedWithSender:(id _Nonnull)sender;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldPerformSegueWithIdentifier:(NSString * _Nonnull)identifier sender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_17IAPViewController")
@interface IAPViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblGame;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblGoods;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPrice;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblAccount;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblCurPoints;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vSnake;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vAlipay;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vUnionPay;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWechat;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vGuestWechat;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vGuestAlipay;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnRecharge;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vGuestPayWay;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPoints;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPayArea;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWarnning;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vBackground;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vAlertBackground;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vSuccessAlert;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWechatAlert;
- (IBAction)onWechatConfirmClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onReturnGameClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onConfirmClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onRechargeClickedWithSender:(id _Nonnull)sender;
- (void)viewDidLoad;
- (void)handleSnakePay;
- (void)handleAlipay;
- (void)handleUnionpay;
- (void)handleWeChat;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_11JSONNDModel")
@interface JSONNDModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_19LoginViewController")
@interface LoginViewController : UIViewController <UIAlertViewDelegate, UITableViewDataSource, UITableViewDelegate, UIViewControllerTransitioningDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblCurUser;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _imgCurUser;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vCurUser;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vLoginByCurUser;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vLoginNotGuestType;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vLoginByType;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnLogin;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnSwitchAccount;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vSnakeLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPhoneLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vGuestLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vThirdLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPhoneNotGuestLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vSnakeNotGuestLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vThirdNotGuestLogin;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified _vCachedAccount;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWorkArea;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vBackground;
- (void)handleMoreUser;
- (IBAction)onLoginClickedWithSender:(id _Nonnull)sender;
- (IBAction)onSwitchAccountClicked:(UIButton * _Nonnull)sender;
- (void)handleGuestLogin;
- (void)handlePhoneLogin;
- (void)handleSnakeLogin;
- (void)handleThirdPartyLogin;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)onDeleteClickedWithSender:(UIButton * _Nonnull)sender;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_28NewPhoneNumberViewController")
@interface NewPhoneNumberViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtVerifyCode;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPhoneNumber;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnConfirm;
@property (nonatomic, weak) IBOutlet CountdownButton * _Null_unspecified _btnVerifyCode;
- (IBAction)onPhoneNumberChangedWithSender:(UITextField * _Nonnull)sender;
- (IBAction)onReacquireClickedWithSender:(CountdownButton * _Nonnull)sender;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onVerifyCodeChangedWithSender:(UITextField * _Nonnull)sender;
- (IBAction)onConfirmClickedWithSender:(UIButton * _Nonnull)sender;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_27PasswordResetViewController")
@interface PasswordResetViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPass;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnPassToggle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnConfirm;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPasswordTips;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onTextChanged:(UITextField * _Nonnull)sender;
- (IBAction)onPassToggleClickedWithSender:(id _Nonnull)sender;
- (IBAction)onConfirmClickedWithSender:(id _Nonnull)sender;
- (void)viewDidLoad;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_34PasswordSetPhoneFillViewController")
@interface PasswordSetPhoneFillViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTips;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnNext;
@property (nonatomic, weak) IBOutlet CountdownButton * _Null_unspecified _btnVerifyCode;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtVerifyCode;
- (IBAction)onVerifyCodeClickedWithSender:(CountdownButton * _Nonnull)sender;
- (IBAction)onNextClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onTextChangedWithSender:(UITextField * _Nonnull)sender;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_35PasswordSuccessSettedViewController")
@interface PasswordSuccessSettedViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnConfirm;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
- (void)viewDidLoad;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (IBAction)onConfirmClickedWithSender:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_23PhoneFillViewController")
@interface PhoneFillViewController : UIViewController <UIScrollViewDelegate, UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPhone;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnNext;
- (IBAction)onPhoneChangedWithPhone:(UITextField * _Nonnull)phone;
- (IBAction)onNextClickedWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLoad;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_24PhoneLoginViewController")
@interface PhoneLoginViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnPassLogin;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnPhoneLogin;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnLogin;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnRegOrFirstLogin;
@property (nonatomic, weak) IBOutlet CountdownButton * _Null_unspecified _btnLoginVerifyCode;
@property (nonatomic, weak) IBOutlet CountdownButton * _Null_unspecified _btnRegOrFistLoginVerifyCode;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblRegOrFirstLoginTips;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblLoginTips;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtRegOrFirstLoginVerifyCode;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtLoginVerifyCode;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPassword;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vRegOrFirstLogin;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vFooter;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _vLawChecke;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vFirstLoginFooter;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vRegisterFooter;
- (IBAction)onVerifyCodeLoginSelectedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onPassLoginSelectedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onVerifyCodeClickedWithSender:(CountdownButton * _Nonnull)sender;
- (IBAction)onRegisterOrFirstLoginClickedWithSender:(id _Nonnull)sender;
- (IBAction)onFAQClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onLoginClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onTextChanged:(UITextField * _Nonnull)sender;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)handleLawCheckImage;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_30PhonePasswordSetViewController")
@interface PhonePasswordSetViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblStrength;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPassword;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnConfirm;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnPasswordConfirm;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnPasswordToggle;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWeak;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vNormal;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vStrong;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPassWillSet;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vPassDidSet;
- (IBAction)onPasswordToggleWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onConfirmSuccessClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onConfirmClickedWithSender:(id _Nonnull)sender;
- (IBAction)onTextChangedWithSender:(UITextField * _Nonnull)sender;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_32PhoneSuccessSettedViewController")
@interface PhoneSuccessSettedViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnReturnLogin;
- (IBAction)onConfirmClickedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)onReturnClickedWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_13PitayaManager")
@interface PitayaManager : NSObject <NSURLSessionDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface PitayaManager (SWIFT_EXTENSION(_CUSTOM_MODULE_NAME_))
/// a delegate method to check whether the remote cartification is the same with given certification.
/// \param session NSURLSession
///
/// \param challenge NSURLAuthenticationChallenge
///
/// \param completionHandler the completionHandler closure
///
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(enum NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end




SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_19PointChooseViewCell")
@interface PointChooseViewCell : UICollectionViewCell <WXApiDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPoint;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _imgSelected;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIAlertView;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_36RechargePlatformChooseViewController")
@interface RechargePlatformChooseViewController : UIViewController <UIAlertViewDelegate, WXApiDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblAccount;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblBalance;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vAlipay;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vUnionPay;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWechat;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vBackground;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWechatAlert;
- (IBAction)onConfirmClickedWithSender:(UIButton * _Nonnull)sender;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)handleAlipay;
- (void)handleUnionpay;
- (void)handleWeChat;
- (void)alertView:(UIAlertView * _Nonnull)alertView clickedButtonAtIndex:(NSInteger)buttonIndex;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_22RechargeViewController")
@interface RechargeViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblAmount;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnRecharge;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vHeader;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified _vPoints;
- (IBAction)onRechargeClickedWithSender:(id _Nonnull)sender;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_31SnakeBindingPhoneViewController")
@interface SnakeBindingPhoneViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPhone;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtVerifyCode;
@property (nonatomic, weak) IBOutlet CountdownButton * _Null_unspecified _btnVerifyCode;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnRegister;
- (IBAction)onVerifyCodeClickedWithSender:(id _Nonnull)sender;
- (IBAction)onRegisterClickedWithSender:(id _Nonnull)sender;
- (IBAction)onTextChanged:(UITextField * _Nonnull)obj;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_33SnakeLoginOrBindingViewController")
@interface SnakeLoginOrBindingViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPass;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtAccount;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnLoginOrBinding;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblSnakeTips;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPasswordTips;
- (IBAction)onLoginOrBindingClickedWithSender:(id _Nonnull)sender;
- (IBAction)onTextChanged:(UITextField * _Nonnull)obj;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_8SnakeRSA")
@interface SnakeRSA : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, DigestType) {
    DigestTypeSHA1 = 0,
    DigestTypeSHA224 = 1,
    DigestTypeSHA256 = 2,
    DigestTypeSHA384 = 3,
    DigestTypeSHA512 = 4,
};


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_13SnakeRSAError")
@interface SnakeRSAError : NSError
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_27SnakeRegisterViewController")
@interface SnakeRegisterViewController : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtAccount;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtPass;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified _txtCaptcha;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnPassToggle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnRegister;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnService;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnPrivate;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _vCaptcha;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _vLawChecker;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblLaw;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblAccountTips;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblPasswordTips;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblVerifyCodeTips;
- (IBAction)onTextChanged:(UITextField * _Nonnull)sender;
- (IBAction)onPassToggleClickedWithSender:(id _Nonnull)sender;
- (IBAction)onRegisterClickedWithSender:(id _Nonnull)sender;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)viewDidLoad;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)handleLawCheck;
- (void)handleCaptcha;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_8SnakeSDK")
@interface SnakeSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SnakeSDK * _Nonnull shareInstace;)
+ (SnakeSDK * _Nonnull)shareInstace SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)onLoginClickBySwiftWithTrans:(NSString * _Nullable)trans;
- (void)onLoginOutClickBySwift;
- (void)onUserCenterClickBySwiftWithTrans:(NSString * _Nullable)trans;
- (void)onPayClickBySwiftWithCount:(NSInteger)count totalAmount:(float)totalAmount productID:(NSString * _Nonnull)productID productName:(NSString * _Nonnull)productName productDesc:(NSString * _Nonnull)productDesc notifyURL:(NSString * _Nonnull)notifyURL transparent:(NSString * _Nonnull)transparent;
- (void)onExitClickBySwift;
- (void)setExtrasWithGame:(NSString * _Nonnull)game roleId:(NSString * _Nonnull)roleId roleName:(NSString * _Nonnull)roleName serverId:(NSString * _Nonnull)serverId serverName:(NSString * _Nonnull)serverName gameUserBalance:(NSString * _Nonnull)gameUserBalance vipLevel:(NSString * _Nonnull)vipLevel gameUserLevel:(NSString * _Nonnull)gameUserLevel partyName:(NSString * _Nonnull)partyName;
- (void)verifyAPPStoreIAPWithReceipt:(NSString * _Nonnull)receipt orderId:(NSString * _Nonnull)orderId productId:(NSString * _Nullable)productId transactionId:(NSString * _Nullable)transactionId completion:(void (^ _Nonnull)(NSInteger, BOOL))completion;
- (void)handlePaymentResultWithUrl:(NSURL * _Nonnull)url;
- (void)sdkInitCallBack;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_29ThirdPartyLoginViewController")
@interface ThirdPartyLoginViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWeChat;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vWeibo;
- (void)handleWeChatLogin;
- (void)handleWeiboLogin;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



@class UITapGestureRecognizer;
@class NSTimer;

@interface UIView (SWIFT_EXTENSION(_CUSTOM_MODULE_NAME_))
- (void)handleToastTapped:(UITapGestureRecognizer * _Nonnull)recognizer;
- (void)toastTimerDidFinish:(NSTimer * _Nonnull)timer;
@end






SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_24UserCenterViewController")
@interface UserCenterViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified _imgAccountType;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vCharge;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vAccount;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vHelper;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTips;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblTitle;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnBindingOrSwitch;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnHelper;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified _btnGuestExit;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified _lblGuestTips;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vGuest;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified _vDashboard;
- (IBAction)onHelperClicked:(UIButton * _Nonnull)sender;
- (IBAction)onGuestExitClicked:(UIButton * _Nonnull)sender;
- (void)handleCharge;
- (void)handleAccount;
- (void)handleHelper;
- (IBAction)onBindingOrSwitchAccountClickedWithSender:(id _Nonnull)sender;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20_CUSTOM_MODULE_NAME_14ViewController")
@interface ViewController : UIViewController
- (IBAction)onLoginClickedWithSender:(id _Nonnull)sender;
- (IBAction)onLogoutClickedWithSender:(id _Nonnull)sender;
- (IBAction)onUserCenterClickedWithSender:(id _Nonnull)sender;
- (IBAction)onPayClickedWithSender:(id _Nonnull)sender;
- (void)viewDidLoad;
- (IBAction)_onQuitClickedWithSender:(UIButton * _Nonnull)sender;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
